Update calculation of light and historic demand in `westeros_baseline` tutorial
iiasa/message_ix pull request #523
Opened 2021-10-18 13:18 UTC by LauWien

This PR updates the calculation of the `light_demand` and `historic_demand` in the `westeros_baseline` tutorial. Closes #522 

## How to review

- Read the diff and note that the CI checks all pass.

## PR checklist

- [x] Continuous integration checks all ✅
- [x] Update release notes.

2021-10-21 07:39 UTC, LauWien commented
> 
> 
> Thanks @LauWien for opening this and resolving inconsistencies. As for the MACRO, I'd suggest you update the Excel file and make the tests pass. Because the layout of data in that Excel file is being used by different modeling streams (global, national, tutorials) for doing MACRO calibration. There are also some suggestions for improving the Excel layout in PR #327. Later, we can decide what to do with that Excel file.

Thank you for your review! I'll do as suggested :)

2021-11-03 10:17 UTC, khaeru requested changes
Looks great, thanks for this clean-up. Only a few minor items to tidy.

2021-11-03 10:17 UTC, khaeru commented on message_ix/tests/test_macro.py
> +        * np.array([20, -7.514287920171298, 43.62562814596503, 21.143463116337838]),
The default relative tolerance for [`assert_allclose`](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html) is 1e-7, so we don't need to include more than that many significant figures.

2021-11-03 10:17 UTC, khaeru commented on message_ix/tests/test_macro.py
> +                26.583631304232025,
Ditto.

2021-11-03 10:17 UTC, khaeru commented on message_ix/testing/__init__.py
> -    # FIXME the value for wind_ppl should be 0.36; requires adjusting other tests.
Thanks for going through and making those adjustments! 🙏🏾

2021-11-03 12:40 UTC, LauWien commented
> 
> 
> Looks great, thanks for this clean-up. Only a few minor items to tidy.

Thank you for your review :)

2021-11-04 07:35 UTC, khaeru approved these changes
There are two more places where we could have also reduced the numbers of figures: test_macro.py around line 138, and test_reporting.py. 

However, LGTM! Those can be tidied the next time a test change requires adjustment to those values.

2021-11-04 08:21 UTC, LauWien commented
> 
> 
> There are two more places where we could have also reduced the numbers of figures: test_macro.py around line 138, and test_reporting.py.
> 
> However, LGTM! Those can be tidied the next time a test change requires adjustment to those values.

Oh yes, I'll do it in this PR https://github.com/iiasa/message_ix/pull/524, where I need to update them again, anyways :) Was maybe not the best idea to open two PRs with changing the same tutorial.

2021-11-04 08:48 UTC, merged