Add information about publication: Energy storage in Central Asia
iiasa/message_ix pull request #682
Opened 2022-12-06 11:31 UTC by behnam-zakeri

This PR adds information on one of publications of MESSAGEix for the list in the "usage" page.

## How to review

Please check out this branch, build the documentation on your machine, and check if the information in the page "[Usage](https://docs.messageix.org/en/stable/usage.html)" about [this publication](https://www.sciencedirect.com/science/article/pii/S2352152X2200603X) reads correctly.

## PR checklist
- [x] Continuous integration checks all ✅
- [x] Tests not needed ✅
- [x] Add, expand, or update documentation.
- [x] Release notes not needed.

2023-02-07 09:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iiasa/message_ix?pullRequest=682) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/iiasa/message_ix?pullRequest=682) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: behnam-zakeri<br/>:x: glatterf42<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iiasa/message_ix?pullRequest=682) it.</sub>

2023-02-07 09:58 UTC, glatterf42 requested changes
I applied black so that the lint check passes. In that process, I also noticed that that we should move the coverage configuration to pyproject.toml as explained [here](https://iiasa-ece.slack.com/archives/CD0GBHHA4/p1674121353182649).
Regarding the documentation, I think it looks good. However, I'd like to see a small change to the phrasing of 'Usage' to make it consistent with the other projects: please use the imperative form, e.g. 'Model the energy-water system of Central Asia with 12 sub-annual time slices and analyze the role of energy and water storage solutions.'
Once that is done (and the checks have passed again), I'll merge this PR.

2023-02-07 10:15 UTC, glatterf42 reviewed
Add the suggestion so that it may be applied directly.

2023-02-07 10:15 UTC, glatterf42 commented on doc/usage.rst
> +- **Usage**: An energy-water system model of Central Asia with 12 sub-annual time slices for modeling and analyzing the role of energy and water storage solutions.
```suggestion
- **Usage**: Model the energy-water system of Central Asia with 12 sub-annual time slices and analyze the role of energy and water storage solutions.
```

2023-02-09 07:58 UTC, behnam-zakeri commented
Thanks @glatterf42 for reviewing this. Very good suggestion for the text, I applied that. The lint errors you mentioned earlier are not related to this PR. This PR originally didn't touch the code, and was only an update to the documentation. So, I assume there has been changes in the version Black that caused new lint errors, or maybe we needed to rebase this PR.

2023-02-09 09:08 UTC, glatterf42 approved these changes

2023-02-09 09:10 UTC, merged